### ISSUE TITLE
Add other types like datepicker

### ISSUE THREAD

**Issue by antoine-pous** [onekiloparsec/vue-xeditable#2]
Hi !

Your version of vue-xeditable is really cool, but it miss most of supported types, can you add them into futures releases?

Thank you !

**Comment by antoine-pous** [comment]
Currently i need only the datepicker and the checklist. I say the most of supported type because you have listed `text, textarea, number, select` while the official version support `text, textarea, select, date, datetime, dateui, combodate, html5types, checklist, wysihtml5, typeahead, typeaheadjs, select2`

Unfortunately i can't help you to improve your component, currently i have too much work :(

**Comment by onekiloparsec** [comment]
Funny to talk about the "official" version. Anyway, datepicker is certainly the next one to be included. Although I am not entirely happy with select yet. But, I should soon hit that problem again and will make sure to start the datepicker.

**Comment by onekiloparsec** [comment]
Datepicker is on its way... (will check the ... checklist too).

**Comment by onekiloparsec** [comment]
datepicker is available. As for the others, I accept PRs, but otherwise, this will move forward only with my needs.
