### ISSUE TITLE
Allow deep get/set of path on nullable objects

### ISSUE THREAD

**Issue by keyboardsamurai** [onekiloparsec/vue-xeditable#4]
I struggle to find a workaround of arrays or properties that might have a null reference in their path. Here is an example:

`<vue-xeditable type="text" name="someArray[0].someProperty" :value="someArray[0].someProperty"  @value-did-change="sendValueDidChangeEvent"/>
`

In the above example `someArray` might be empty and contain no element with index 0. The current behavior is to just fail. Wouldn't it be better to allow deep setting and dynamic adding of elements? Kind of like lodash set does it https://lodash.com/docs/4.17.10#set

**Comment by onekiloparsec** [comment]
Anything is probably better that "just fail" of course! :-) I welcome a PR if you can (I'm pretty busy right now and could promise to spend time on that).

**Comment by keyboardsamurai** [comment]
I will have a look and see if I can resolve the issue.

**Comment by onekiloparsec** [comment]
Working on the component these days, and reading again your issue. I am not sure it is the responsability of the component to actually handle nested/deep objects. Do you still have the problem ?

**Comment by keyboardsamurai** [comment]
I ended up working around it by just passing the path string to a handler methods that would then evaluate the nested structure via lodash. It’s an awkward fix that could be avoided by making the component take care of these cases.

However I was not able to create a patch that wouldn’t have introduced major dependencies.

**Comment by onekiloparsec** [comment]
Ok
